export const version = "1.7.4";
export const hostname = "http://"+ window.location.hostname;
export const apiUrl = hostname +":3301";
export const pluginUrl = "https://cdn.jsdelivr.net/gh/nocpiun/ferrum-plugins@latest/";
export const pluginListUrl = pluginUrl +"manifest.json";
export const editorDefaultValue = "HelloWorld.\nWelcome to use ferrum!\n\nGithub Repo: https://github.com/NriotHrreion/ferrum";
export const pluginStorageKey = "ferrum.external";
export const langStorageKey = "ferrum.lang";
export type langStorageType = { language: string };
